### ISSUE TITLE
Small Fixes

### ISSUE THREAD

**Issue by moizsyed** [jgonera/howwrong#36]
- [x] Mobile view "next question" buttons on quiz and on questions next to be turned smaller when scrolled, button should just say "next"
- [ ] Quiz desktop layout should be the same as question desktop
- [x] Footer quizzes
- [ ] Make footer nicer.

**Comment by jgonera** [comment]
"Make footer nicer" sounds ambiguous. "Quiz desktop layout should be the same as question desktop" to a separate issue.
